intake
FRC-7525/2024-Progathon pull request #2
Opened 2024-12-23 01:55 UTC by PotmanNob

w intake trust trust

2024-12-24 00:32 UTC, GreenTomato5 requested changes
mostly fire

2024-12-24 00:32 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/Constants.java
Rename to IntakeConstants

2024-12-24 00:32 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/Constants.java
> +    public final static PIDConstants PIVOT_PID_CONSTANTS = new PIDConstants(0, 0, 0);
guess and check PID with sim

2024-12-24 00:32 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeIOSim.java
> +    SingleJointedArmSim pivotSim;
make all these private

2024-12-26 19:59 UTC, GreenTomato5 approved these changes
Best code I've ever seen

2024-12-26 19:59 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeIOReal.java
> +        inputs.pivotPosition = Units.rotationsToDegrees(pivotMotor.getPosition().getValueAsDouble());
Specifically for the IO real, use smart dashboard to log the PID controller if you're in testing mode (Should be renamed to tuning if its not already)

2024-12-26 19:59 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeIOReal.java
> +        pivotMotor = new TalonFX(IntakeConstants.Real.PIVOT_MOTOR_CANID);
you have to zero the encoder for the pivot should be pivotMotor.setPosition(0)

2024-12-26 19:59 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeIOSim.java
> +
If you don't want to add ctre sim with the wpilib physics sim open an issue about it so sum1 else can do it once this is merged

2024-12-26 19:59 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeStates.java
> +    IntakeStates(Double wheelSpeed, double pivotSetpoint, String stateString) {
Ok buddy put state string first

2024-12-26 19:59 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Manager/ManagerStates.java
> +    public IntakeStates getIntakeState() {
cant this be protected?

2024-12-26 19:59 UTC, GreenTomato5 requested changes
I meant to request c hanges (see the comments)

2024-12-28 00:44 UTC, PotmanNob commented on src/main/java/frc/robot/subsystems/Intake/IntakeStates.java
> +    IntakeStates(Double wheelSpeed, double pivotSetpoint, String stateString) {
buddy is a hater

2024-12-28 01:28 UTC, GreenTomato5 requested changes
Almost!

2024-12-28 01:28 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/Intake.java
> +        Logger.recordOutput("Intake State", getState());
this logs output to the "recorded outputs" dir in ascope, you should do SUBSYSTEM_NAME/ + "Intake State" and store subsystem name in constants. Same for all other logs

2024-12-28 01:28 UTC, GreenTomato5 commented on src/main/java/frc/robot/subsystems/Intake/IntakeIOReal.java
> +            SendableRegistry.setName(pivotController, "Intake", "Pivot PIDController");
Check the thing I said in call?

2024-12-28 01:37 UTC, GreenTomato5 approved these changes
Work on your commit messages

2024-12-28 19:44 UTC, merged